const potentialAnswers = {
  "NFL": [
    ["Emmitt Smith", "Walter Payton", "Barry Sanders", "Jim Brown", "Adrian Peterson", "Frank Gore", "LaDainian Tomlinson", "Eric Dickerson", "Tony Dorsett", "Marshawn Lynch"],
    ["Tom Brady", "Joe Montana", "Terry Bradshaw", "Peyton Manning", "John Elway", "Ben Roethlisberger", "Eli Manning", "Joe Flacco", "Patrick Mahomes", "Brett Favre"],
    ["New England Patriots", "Dallas Cowboys", "Pittsburgh Steelers", "San Francisco 49ers", "Denver Broncos", "Washington Commanders", "Green Bay Packers", "Miami Dolphins", "Philadelphia Eagles", "Kansas City Chiefs"],
    ["John Ross", "Chris Johnson", "Xavier Worthy", "Tyreek Hill", "Kalif Raymond", "Darius Shepherd", "Jalen Myrick", "Henry Ruggs III", "Marquise Goodwin", "DeSean Jackson"],
    ["Bruce Smith", "Reggie White", "DeMarcus Ware", "Julius Peppers", "Kevin Greene", "Richard Dent", "Jason Taylor", "Terrell Suggs", "Chris Doleman", "J.J. Watt"],
    ["New England Patriots", "Pittsburgh Steelers", "Green Bay Packers", "Seattle Seahawks", "Philadelphia Eagles", "Indianapolis Colts", "Kansas City Chiefs", "Baltimore Ravens", "San Francisco 49ers", "Dallas Cowboys"],
    ["Patrick Mahomes", "Jalen Hurts", "Joe Burrow", "Josh Allen", "Lamar Jackson", "Dak Prescott", "Aaron Rodgers", "Justin Herbert", "Kyler Murray", "Russell Wilson"],
    ["Peyton Manning", "Patrick Mahomes", "Tom Brady", "Dan Marino", "Drew Brees", "Matt Ryan", "Ben Roethlisberger", "Philip Rivers", "Joe Burrow", "Andrew Luck"],
    ["New England Patriots", "Pittsburgh Steelers", "Denver Broncos", "San Francisco 49ers", "Dallas Cowboys", "Green Bay Packers", "Miami Dolphins", "New York Giants", "Philadelphia Eagles", "Kansas City Chiefs"],
    ["Calvin Johnson", "Jerry Rice", "Randy Moss", "Terrell Owens", "Marvin Harrison", "Steve Smith Sr.", "Larry Fitzgerald", "Andre Johnson", "Julio Jones", "A.J. Green"],
    ["Patrick Mahomes", "Tom Brady", "Aaron Rodgers", "Joe Montana", "Joe Flacco", "Eli Manning", "Russell Wilson", "Ben Roethlisberger", "Kurt Warner", "Steve Young"],
    ["New England Patriots", "Seattle Seahawks", "Green Bay Packers", "Dallas Cowboys", "Pittsburgh Steelers", "Kansas City Chiefs", "Philadelphia Eagles", "San Francisco 49ers", "Baltimore Ravens", "New York Giants"],
    ["Rod Woodson", "Charles Woodson", "Darrelle Revis", "Deion Sanders", "Aqib Talib", "Asante Samuel", "Ed Reed", "Ronnie Lott", "Troy Polamalu", "Ty Law"],
    ["Kansas City Chiefs", "Philadelphia Eagles", "Cincinnati Bengals", "Los Angeles Rams", "San Francisco 49ers", "Buffalo Bills", "Detroit Lions", "Miami Dolphins", "Tampa Bay Buccaneers", "New York Jets"],
    ["Tom Brady", "Peyton Manning", "Brett Favre", "Drew Brees", "Dan Marino", "John Elway", "Ben Roethlisberger", "Philip Rivers", "Matt Ryan", "Aaron Rodgers"],
    ["Adrian Peterson", "Jamal Lewis", "Walter Payton", "O.J. Simpson", "Ahman Green", "Chris Johnson", "DeAngelo Williams", "LeSean McCoy", "Derrick Henry", "Barry Sanders"],
    ["Cleveland Browns", "Detroit Lions", "Houston Texans", "Jacksonville Jaguars", "Arizona Cardinals", "New York Jets", "Buffalo Bills", "Carolina Panthers", "Atlanta Falcons", "Minnesota Vikings"],
    ["Ray Lewis", "Junior Seau", "London Fletcher", "Zach Thomas", "Patrick Willis", "Brian Urlacher", "Derrick Brooks", "Mike Singletary", "Luke Kuechly", "Bobby Wagner"],
    ["Tom Brady", "Peyton Manning", "Joe Montana", "Brett Favre", "Kurt Warner", "Earl Morrall", "Craig Morton", "Jim Plunkett", "Russell Wilson", "John Elway"],
    ["Chicago Bears", "Green Bay Packers", "New York Giants", "Pittsburgh Steelers", "Dallas Cowboys", "Washington Commanders", "San Francisco 49ers", "Philadelphia Eagles", "Kansas City Chiefs", "Miami Dolphins"],
    ["Devin Hester", "Deion Sanders", "Eric Metcalf", "Darren Sproles", "Josh Cribbs", "Dante Hall", "LeRoy Butler", "Tim Brown", "Desmond Howard", "Tavon Austin"],
    ["Tom Brady", "Peyton Manning", "Brett Favre", "Drew Brees", "Dan Marino", "John Elway", "Ben Roethlisberger", "Philip Rivers", "Matt Ryan", "Aaron Rodgers"],
    ["Adrian Peterson", "LaDainian Tomlinson", "Marshall Faulk", "Walter Payton", "Earl Campbell", "Barry Sanders", "Emmitt Smith", "Terrell Davis", "Shaun Alexander", "Jim Brown"],
    ["San Francisco 49ers", "Dallas Cowboys", "Pittsburgh Steelers", "New York Giants", "Washington Commanders", "Green Bay Packers", "Philadelphia Eagles", "Kansas City Chiefs", "Seattle Seahawks", "New England Patriots"],
    ["Patrick Mahomes", "Joe Burrow", "Josh Allen", "Jalen Hurts", "Lamar Jackson", "Justin Herbert", "Aaron Rodgers", "Russell Wilson", "Dak Prescott", "Kyler Murray"],
    ["Kansas City Chiefs", "San Francisco 49ers", "Philadelphia Eagles", "Green Bay Packers", "Tampa Bay Buccaneers", "Los Angeles Rams", "New York Giants", "Seattle Seahawks", "Baltimore Ravens", "Denver Broncos"],
    ["Jerry Rice", "Randy Moss", "Terrell Owens", "Marvin Harrison", "Cris Carter", "Steve Largent", "Tim Brown", "Don Hutson", "Larry Fitzgerald", "Calvin Johnson"],
    ["Tony Gonzalez", "Peyton Manning", "Bruce Matthews", "Jerry Rice", "Randy Moss", "Terrell Owens", "Marvin Harrison", "Jason Witten", "Kellen Winslow", "Rob Gronkowski"],
    ["New England Patriots", "Miami Dolphins", "Chicago Bears", "San Francisco 49ers", "Dallas Cowboys", "Indianapolis Colts", "Kansas City Chiefs", "Green Bay Packers", "Pittsburgh Steelers", "Philadelphia Eagles"],
    ["Bryce Young", "C.J. Stroud", "Trevor Lawrence", "Joe Burrow", "Kyler Murray", "Baker Mayfield", "Sam Darnold", "Josh Rosen", "Jared Goff", "Carson Wentz"],
    ["Tom Brady", "Peyton Manning", "John Elway", "Brett Favre", "Dan Marino", "Joe Montana", "Ben Roethlisberger", "Eli Manning", "Drew Brees", "Aaron Rodgers"],
    ["Dallas Cowboys", "Green Bay Packers", "Pittsburgh Steelers", "New England Patriots", "San Francisco 49ers", "Miami Dolphins", "Washington Commanders", "Chicago Bears", "Philadelphia Eagles", "Kansas City Chiefs"],
    ["Adam Vinatieri", "Morten Andersen", "Gary Anderson", "Jason Hanson", "John Carney", "Matt Prater", "Robbie Gould", "Sebastian Janikowski", "Phil Dawson", "Justin Tucker"],
    ["Nick Bosa", "T.J. Watt", "Myles Garrett", "Aaron Donald", "Stephon Gilmore", "Jalen Ramsey", "Khalil Mack", "Von Miller", "Joey Bosa", "Micah Parsons"],
    ["New England Patriots", "Pittsburgh Steelers", "San Francisco 49ers", "Dallas Cowboys", "Green Bay Packers", "Philadelphia Eagles", "Kansas City Chiefs", "Seattle Seahawks", "Baltimore Ravens", "New York Giants"],
    ["Emmitt Smith", "LaDainian Tomlinson", "Walter Payton", "Adrian Peterson", "Barry Sanders", "Jim Brown", "Marcus Allen", "Franco Harris", "Thurman Thomas", "Ezekiel Elliott"],
    ["Tom Brady", "Joe Flacco", "Eli Manning", "Peyton Manning", "Joe Montana", "Aaron Rodgers", "Ben Roethlisberger", "Drew Brees", "Russell Wilson", "Patrick Mahomes"],
    ["Denver Broncos", "New England Patriots", "Dallas Cowboys", "San Francisco 49ers", "Miami Dolphins", "Buffalo Bills", "Minnesota Vikings", "Washington Commanders", "Philadelphia Eagles", "Kansas City Chiefs"],
    ["Brian Mitchell", "Devin Hester", "Tim Brown", "Darren Sproles", "Josh Cribbs", "Dante Hall", "Desmond Howard", "Tavon Austin", "DeSean Jackson", "Cordarrelle Patterson"],
    ["Jerry Rice", "Terrell Owens", "Randy Moss", "Marvin Harrison", "Cris Carter", "Steve Largent", "Tim Brown", "Don Hutson", "Larry Fitzgerald", "Calvin Johnson"],
    ["New England Patriots", "Pittsburgh Steelers", "New York Giants", "Baltimore Ravens", "Seattle Seahawks", "Philadelphia Eagles", "Green Bay Packers", "Denver Broncos", "Kansas City Chiefs", "San Francisco 49ers"],
    ["Rod Woodson", "Deion Sanders", "Aqib Talib", "Charles Woodson", "Darrelle Revis", "Ed Reed", "Ronnie Lott", "Troy Polamalu", "Ty Law", "Champ Bailey"],
    ["Aaron Rodgers", "Peyton Manning", "Russell Wilson", "Tom Brady", "Drew Brees", "Patrick Mahomes", "Joe Montana", "Ben Roethlisberger", "Matt Ryan", "Philip Rivers"],
    ["New England Patriots", "Pittsburgh Steelers", "Denver Broncos", "Oakland Raiders", "Indianapolis Colts", "Kansas City Chiefs", "Miami Dolphins", "Buffalo Bills", "Baltimore Ravens", "Cincinnati Bengals"],
    ["Josh Cribbs", "Devin Hester", "Leon Washington", "Cordarrelle Patterson", "Jacoby Ford", "Dante Hall", "Ted Ginn Jr.", "Percy Harvin", "DeSean Jackson", "Tyreek Hill"],
    ["Justin Jefferson", "Ja’Marr Chase", "Garrett Wilson", "Najee Harris", "Penei Sewell", "Micah Parsons", "Rashawn Slater", "Trevor Lawrence", "Kyle Pitts", "Jaylen Waddle"],
    ["New England Patriots", "Indianapolis Colts", "Green Bay Packers", "Philadelphia Eagles", "Seattle Seahawks", "Kansas City Chiefs", "Pittsburgh Steelers", "San Francisco 49ers", "Dallas Cowboys", "Baltimore Ravens"],
    ["Brett Favre", "Tom Brady", "Peyton Manning", "Drew Brees", "Dan Marino", "John Elway", "Ben Roethlisberger", "Philip Rivers", "Matt Ryan", "Aaron Rodgers"],
    ["Tom Brady", "Peyton Manning", "John Elway", "Brett Favre", "Dan Marino", "Joe Montana", "Ben Roethlisberger", "Eli Manning", "Drew Brees", "Aaron Rodgers"],
    ["Denver Broncos", "New England Patriots", "Pittsburgh Steelers", "Kansas City Chiefs", "San Francisco 49ers", "Green Bay Packers", "Dallas Cowboys", "Philadelphia Eagles", "Seattle Seahawks", "Baltimore Ravens"]
  ],
  "Golf": [
    ["Jack Nicklaus", "Tiger Woods", "Arnold Palmer", "Tom Watson", "Gary Player", "Sam Snead", "Ben Hogan", "Phil Mickelson", "Rory McIlroy", "Jordan Spieth"],
    ["14", "13", "12", "15", "16", "10", "8", "20", "18", "11"],
    ["Sam Snead", "Tiger Woods", "Jack Nicklaus", "Arnold Palmer", "Ben Hogan", "Phil Mickelson", "Gary Player", "Tom Watson", "Rory McIlroy", "Jordan Spieth"],
    ["Jack Nicklaus", "Tiger Woods", "Gary Player", "Ben Hogan", "Gene Sarazen", "Arnold Palmer", "Tom Watson", "Phil Mickelson", "Rory McIlroy", "Jordan Spieth"],
    ["Jon Rahm", "Brooks Koepka", "Rory McIlroy", "Scottie Scheffler", "Xander Schauffele", "Patrick Reed", "Dustin Johnson", "Bryson DeChambeau", "Collin Morikawa", "Justin Thomas"],
    ["72", "70", "71", "68", "69", "73", "74", "75", "76", "77"],
    ["Brandt Snedeker", "Xander Schauffele", "Rory McIlroy", "Henrik Stenson", "Phil Mickelson", "Justin Rose", "Jordan Spieth", "Dustin Johnson", "Brooks Koepka", "Tiger Woods"],
    ["Jack Nicklaus", "Tiger Woods", "Walter Hagen", "Ben Hogan", "Gary Player", "Tom Watson", "Arnold Palmer", "Phil Mickelson", "Rory McIlroy", "Jordan Spieth"],
    ["400-500 yards", "300-400 yards", "500-600 yards", "200-300 yards", "600-700 yards", "100-200 yards", "700-800 yards", "800-900 yards", "50-100 yards", "900-1000 yards"],
    ["Justin Thomas", "Will Zalatoris", "Mito Pereira", "Rory McIlroy", "Scottie Scheffler", "Xander Schauffele", "Patrick Reed", "Dustin Johnson", "Bryson DeChambeau", "Collin Morikawa"],
    ["Nick Faldo", "Sergio Garcia", "Colin Montgomerie", "Lee Westwood", "Ian Woosnam", "Bernhard Langer", "Seve Ballesteros", "José María Olazábal", "Luke Donald", "Justin Rose"],
    ["Masters", "U.S. Open", "PGA Championship", "The Open Championship", "Players Championship", "FedEx Cup", "Ryder Cup", "Presidents Cup", "Olympic Gold", "World Golf Championships"],
    ["Willie Anderson", "Bobby Jones", "Ben Hogan", "Jack Nicklaus", "Tiger Woods", "Gary Player", "Arnold Palmer", "Phil Mickelson", "Rory McIlroy", "Jordan Spieth"],
    ["Mike Austin", "Carl Cooper", "Shaun Micheel", "Dustin Johnson", "Bubba Watson", "Rory McIlroy", "Bryson DeChambeau", "Jon Rahm", "Cameron Champ", "Kyle Berkshire"],
    ["Brian Harman", "Cameron Young", "Tommy Fleetwood", "Rory McIlroy", "Scottie Scheffler", "Xander Schauffele", "Patrick Reed", "Dustin Johnson", "Bryson DeChambeau", "Collin Morikawa"],
    ["1.68 inches", "1.70 inches", "1.66 inches", "1.72 inches", "1.74 inches", "1.76 inches", "1.78 inches", "1.80 inches", "1.82 inches", "1.84 inches"],
    ["Tiger Woods", "Jack Nicklaus", "Gary Player", "Arnold Palmer", "Phil Mickelson", "Rory McIlroy", "Jordan Spieth", "Dustin Johnson", "Bryson DeChambeau", "Collin Morikawa"],
    ["Bobby Jones", "Alister MacKenzie", "Perry Maxwell", "Tom Fazio", "Jack Nicklaus", "Arnold Palmer", "Gary Player", "Phil Mickelson", "Rory McIlroy", "Jordan Spieth"],
    ["20", "18", "15", "12", "10", "8", "6", "4", "2", "1"],
    ["Tiger Woods", "Phil Mickelson", "Steve Stricker", "Jim Furyk", "Dustin Johnson", "Justin Thomas", "Jordan Spieth", "Rory McIlroy", "Brooks Koepka", "Xander Schauffele"],
    ["Matt Fitzpatrick", "Scottie Scheffler", "Will Zalatoris", "Rory McIlroy", "Xander Schauffele", "Patrick Reed", "Dustin Johnson", "Bryson DeChambeau", "Collin Morikawa", "Justin Thomas"],
    ["Golden Bell", "Amen Corner", "Raes Creek", "Magnolia Lane", "Eisenhower Tree", "Hogan Bridge", "Sarazen Bridge", "Nelson Bridge", "Butler Cabin", "Crow's Nest"],
    ["Jack Nicklaus", "Tiger Woods", "Phil Mickelson", "Arnold Palmer", "Gary Player", "Tom Watson", "Ben Hogan", "Rory McIlroy", "Jordan Spieth", "Dustin Johnson"],
    ["No limit", "10", "8", "6", "4", "2", "1", "12", "14", "16"],
    ["Tiger Woods", "Jack Nicklaus", "Tom Watson", "Arnold Palmer", "Gary Player", "Ben Hogan", "Phil Mickelson", "Rory McIlroy", "Jordan Spieth", "Dustin Johnson"],
    ["Oak Hill", "Valhalla", "Pebble Beach", "Augusta National", "St. Andrews", "Pinehurst", "Bethpage Black", "Shinnecock Hills", "Winged Foot", "Hazeltine National"],
    ["Hideki Matsuyama", "Dustin Johnson", "Jon Rahm", "Scottie Scheffler", "Xander Schauffele", "Patrick Reed", "Bryson DeChambeau", "Collin Morikawa", "Justin Thomas", "Rory McIlroy"],
    ["2.75 inches", "2.5 inches", "3 inches", "3.25 inches", "3.5 inches", "4 inches", "4.5 inches", "5 inches", "5.5 inches", "6 inches"],
    ["Robert Allenby", "Hal Sutton", "Gary Player", "Tiger Woods", "Phil Mickelson", "Rory McIlroy", "Jordan Spieth", "Dustin Johnson", "Bryson DeChambeau", "Collin Morikawa"],
    ["Jack Neville", "Douglas Grant", "Alister MacKenzie", "Bobby Jones", "Tom Fazio", "Jack Nicklaus", "Arnold Palmer", "Gary Player", "Phil Mickelson", "Rory McIlroy"],
    ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"],
    ["Seve Ballesteros", "Bernhard Langer", "Colin Montgomerie", "Nick Faldo", "Sergio Garcia", "Lee Westwood", "Ian Woosnam", "José María Olazábal", "Luke Donald", "Justin Rose"],
    ["Collin Morikawa", "Brooks Koepka", "Justin Thomas", "Rory McIlroy", "Scottie Scheffler", "Xander Schauffele", "Patrick Reed", "Dustin Johnson", "Bryson DeChambeau", "Jon Rahm"],
    ["Tom Morris", "Old Tom", "Valley of Sin", "Road Hole", "Swilcan Bridge", "Hell Bunker", "Eden", "Cardinal", "Strath", "Granny Clark"],
    ["Gary Player", "Bernhard Langer", "Hale Irwin", "Jack Nicklaus", "Tiger Woods", "Phil Mickelson", "Arnold Palmer", "Tom Watson", "Rory McIlroy", "Jordan Spieth"],
    ["1.62 ounces", "1.60 ounces", "1.64 ounces", "1.66 ounces", "1.68 ounces", "1.70 ounces", "1.72 ounces", "1.74 ounces", "1.76 ounces", "1.78 ounces"],
    ["Jack Nicklaus", "Tiger Woods", "Arnold Palmer", "Gary Player", "Phil Mickelson", "Rory McIlroy", "Jordan Spieth", "Dustin Johnson", "Bryson DeChambeau", "Collin Morikawa"],
    ["Pebble Beach", "Augusta National", "St. Andrews", "Pinehurst", "Bethpage Black", "Shinnecock Hills", "Winged Foot", "Hazeltine National", "Oak Hill", "Valhalla"],
    ["Shane Lowry", "Tommy Fleetwood", "Tony Finau", "Rory McIlroy", "Scottie Scheffler", "Xander Schauffele", "Patrick Reed", "Dustin Johnson", "Bryson DeChambeau", "Collin Morikawa"],
    ["4.25 inches", "4.20 inches", "4.30 inches", "4.35 inches", "4.40 inches", "4.45 inches", "4.50 inches", "4.55 inches", "4.60 inches", "4.65 inches"],
    ["Gary Player", "Seve Ballesteros", "Greg Norman", "Nick Faldo", "Bernhard Langer", "Colin Montgomerie", "Sergio Garcia", "Lee Westwood", "Ian Woosnam", "José María Olazábal"],
    ["Donald Ross", "Alister MacKenzie", "Bobby Jones", "Tom Fazio", "Jack Nicklaus", "Arnold Palmer", "Gary Player", "Phil Mickelson", "Rory McIlroy", "Jordan Spieth"],
    ["-3", "-2", "-1", "0", "1", "2", "3", "4", "5", "6"],
    ["Tiger Woods", "Jordan Spieth", "Collin Morikawa", "Justin Thomas", "Rory McIlroy", "Scottie Scheffler", "Xander Schauffele", "Patrick Reed", "Dustin Johnson", "Bryson DeChambeau"],
    ["Scottie Scheffler", "Jon Rahm", "Rory McIlroy", "Xander Schauffele", "Patrick Reed", "Dustin Johnson", "Bryson DeChambeau", "Collin Morikawa", "Justin Thomas", "Brooks Koepka"],
    ["34-35 inches", "32-33 inches", "36-37 inches", "38-39 inches", "40-41 inches", "42-43 inches", "44-45 inches", "46-47 inches", "48-49 inches", "50-51 inches"],
    ["Tiger Woods", "Phil Mickelson", "Rory McIlroy", "Jordan Spieth", "Dustin Johnson", "Justin Thomas", "Brooks Koepka", "Xander Schauffele", "Jon Rahm", "Scottie Scheffler"],
    ["Pete Dye", "Alister MacKenzie", "Bobby Jones", "Tom Fazio", "Jack Nicklaus", "Arnold Palmer", "Gary Player", "Phil Mickelson", "Rory McIlroy", "Jordan Spieth"],
    ["-4", "-3", "-2", "-1", "0", "1", "2", "3", "4", "5"],
    ["Bobby Jones", "Tiger Woods", "Phil Mickelson", "Jack Nicklaus", "Arnold Palmer", "Gary Player", "Tom Watson", "Rory McIlroy", "Jordan Spieth", "Dustin Johnson"]
  ],
  "Soccer": [
    ["Lionel Messi", "Cristiano Ronaldo", "Johan Cruyff", "Michel Platini", "Marco van Basten", "Zinedine Zidane", "Ronaldo", "Franz Beckenbauer", "Alfredo Di Stéfano", "Luka Modrić"],
    ["Brazil", "Germany", "Italy", "Argentina", "France", "Uruguay", "England", "Spain", "Netherlands", "Portugal"],
    ["Alan Shearer", "Harry Kane", "Wayne Rooney", "Andy Cole", "Sergio Agüero", "Frank Lampard", "Thierry Henry", "Robbie Fowler", "Jermain Defoe", "Michael Owen"],
    ["Real Madrid", "AC Milan", "Liverpool", "Bayern Munich", "Barcelona", "Ajax", "Manchester United", "Juventus", "Inter Milan", "Chelsea"],
    ["Kylian Mbappé", "Lionel Messi", "Harry Kane", "Olivier Giroud", "Julián Álvarez", "Richarlison", "Cody Gakpo", "Álvaro Morata", "Marcus Rashford", "Bukayo Saka"],
    ["Cristiano Ronaldo", "Lionel Messi", "Ali Daei", "Pelé", "Ferenc Puskás", "Romário", "Neymar", "Sunil Chhetri", "Mokhtar Dahari", "Robert Lewandowski"],
    ["90 minutes", "80 minutes", "100 minutes", "120 minutes", "60 minutes", "70 minutes", "110 minutes", "130 minutes", "45 minutes", "30 minutes"],
    ["Qatar", "Russia", "Brazil", "South Africa", "Germany", "South Korea/Japan", "France", "USA", "Mexico", "Italy"],
    ["Casemiro", "Neymar", "Thiago Silva", "Marquinhos", "Alisson Becker", "Ederson", "Danilo", "Éder Militão", "Fred", "Lucas Paquetá"],
    ["Manchester United", "Liverpool", "Arsenal", "Chelsea", "Manchester City", "Tottenham Hotspur", "Everton", "Newcastle United", "Aston Villa", "West Ham United"],
    ["Lionel Messi", "Erling Haaland", "Kylian Mbappé", "Kevin De Bruyne", "Robert Lewandowski", "Karim Benzema", "Neymar", "Harry Kane", "Mohamed Salah", "Luka Modrić"],
    ["Lionel Messi", "Xavi Hernández", "Ángel Di María", "Andrés Iniesta", "Toni Kroos", "Jordi Alba", "Karim Benzema", "Dani Alves", "Luis Suárez", "Gerard Piqué"],
    ["Unfair advantage", "Goal scoring", "Foul play", "Offensive strategy", "Defensive strategy", "Player substitution", "Time wasting", "Ball possession", "Free kicks", "Corner kicks"],
    ["Italy", "England", "France", "Spain", "Germany", "Portugal", "Netherlands", "Belgium", "Croatia", "Denmark"],
    ["Cristiano Ronaldo", "Karim Benzema", "Raúl", "Alfredo Di Stéfano", "Santillana", "Hugo Sánchez", "Ferenc Puskás", "Emilio Butragueño", "Gareth Bale", "Zinedine Zidane"],
    ["Independiente", "Boca Juniors", "Peñarol", "River Plate", "Nacional", "São Paulo", "Palmeiras", "Flamengo", "Grêmio", "Santos"],
    ["Emiliano Martínez", "Dominik Livaković", "Yassine Bounou", "Hugo Lloris", "Thibaut Courtois", "Manuel Neuer", "Alisson Becker", "Ederson", "Marc-André ter Stegen", "David de Gea"],
    ["Gerardo Bedoya", "Sergio Ramos", "Pepe", "Felipe Melo", "Luis Suárez", "Marco Materazzi", "John Terry", "Zlatan Ibrahimović", "Mario Balotelli", "Diego Costa"],
    ["8x24 feet", "7x21 feet", "6x18 feet", "9x27 feet", "5x15 feet", "10x30 feet", "4x12 feet", "3x9 feet", "2x6 feet", "1x3 feet"],
    ["Russia", "Qatar", "Brazil", "South Africa", "Germany", "South Korea/Japan", "France", "USA", "Mexico", "Italy"],
    ["Pep Guardiola", "Jürgen Klopp", "Erik ten Hag", "Mikel Arteta", "Thomas Tuchel", "José Mourinho", "Mauricio Pochettino", "Unai Emery", "Eddie Howe", "Graham Potter"],
    ["Arsenal", "Manchester United", "Chelsea", "Liverpool", "Tottenham Hotspur", "Everton", "Newcastle United", "Aston Villa", "West Ham United", "Leicester City"],
    ["Lionel Messi", "Robert Lewandowski", "Jorginho", "Karim Benzema", "N’Golo Kanté", "Kevin De Bruyne", "Kylian Mbappé", "Cristiano Ronaldo", "Neymar", "Mohamed Salah"],
    ["Alan Shearer", "Harry Kane", "Sergio Agüero", "Wayne Rooney", "Andy Cole", "Frank Lampard", "Thierry Henry", "Robbie Fowler", "Jermain Defoe", "Michael Owen"],
    ["5", "3", "4", "6", "7", "8", "9", "10", "11", "12"],
    ["Germany", "Brazil", "Argentina", "Spain", "Italy", "France", "Uruguay", "England", "Netherlands", "Portugal"],
    ["Lionel Messi", "Luis Suárez", "Johan Cruyff", "Ronaldo", "Ronaldinho", "Rivaldo", "Neymar", "Samuel Eto’o", "Andrés Iniesta", "Xavi Hernández"],
    ["Real Madrid", "Barcelona", "Atlético Madrid", "Valencia", "Sevilla", "Athletic Bilbao", "Deportivo La Coruña", "Real Sociedad", "Espanyol", "Real Betis"],
    ["Real Madrid", "Manchester City", "Chelsea", "Liverpool", "Bayern Munich", "Paris Saint-Germain", "Juventus", "Inter Milan", "Borussia Dortmund", "Manchester United"],
    ["Lionel Messi", "Kevin De Bruyne", "Neymar", "Ángel Di María", "Xavi Hernández", "Andrés Iniesta", "Toni Kroos", "Jordi Alba", "Karim Benzema", "Dani Alves"],
    ["8.6-9 inches", "8-8.5 inches", "9-9.5 inches", "7.5-8 inches", "9.5-10 inches", "10-10.5 inches", "7-7.5 inches", "6.5-7 inches", "10.5-11 inches", "11-11.5 inches"],
    ["South Africa", "Qatar", "Russia", "Brazil", "Germany", "South Korea/Japan", "France", "USA", "Mexico", "Italy"],
    ["Lionel Messi", "Ángel Di María", "Juan Román Riquelme", "Emiliano Martínez", "Lautaro Martínez", "Rodrigo De Paul", "Leandro Paredes", "Gonzalo Montiel", "Nicolás Otamendi", "Julián Álvarez"],
    ["Juventus", "AS Roma", "Inter Milan", "AC Milan", "Napoli", "Lazio", "Fiorentina", "Torino", "Sampdoria", "Bologna"],
    ["Lionel Messi", "Erling Haaland", "Kylian Mbappé", "Kevin De Bruyne", "Robert Lewandowski", "Karim Benzema", "Neymar", "Harry Kane", "Mohamed Salah", "Luka Modrić"],
    ["Erling Haaland", "Mohamed Salah", "Harry Kane", "Alan Shearer", "Wayne Rooney", "Andy Cole", "Frank Lampard", "Thierry Henry", "Robbie Fowler", "Jermain Defoe"],
    ["100-110 meters", "90-100 meters", "110-120 meters", "80-90 meters", "120-130 meters", "70-80 meters", "60-70 meters", "50-60 meters", "40-50 meters", "30-40 meters"],
    ["Italy", "Brazil", "Germany", "Argentina", "France", "Uruguay", "England", "Spain", "Netherlands", "Portugal"],
    ["Wayne Rooney", "Bobby Charlton", "Denis Law", "Cristiano Ronaldo", "George Best", "Eric Cantona", "Ryan Giggs", "Paul Scholes", "David Beckham", "Ruud van Nistelrooy"],
    ["Bayern Munich", "Borussia Dortmund", "Hamburger SV", "Werder Bremen", "VfB Stuttgart", "Borussia Mönchengladbach", "Eintracht Frankfurt", "Schalke 04", "Bayer Leverkusen", "RB Leipzig"],
    ["Karim Benzema", "Lionel Messi", "Robert Lewandowski", "Kylian Mbappé", "Kevin De Bruyne", "Neymar", "Harry Kane", "Mohamed Salah", "Luka Modrić", "Erling Haaland"],
    ["Petr Čech", "David James", "Mark Schwarzer", "David Seaman", "Pepe Reina", "Edwin van der Sar", "Tim Howard", "Brad
