// Quiz data for Ball Knowledge - Updated for March 7, 2025
const quizData = {
  "NFL": [
    { text: "Name one of the top 5 NFL rushers of all time.", solutions: ["Emmitt Smith", "Walter Payton", "Barry Sanders", "Jim Brown", "Adrian Peterson"] },
    { text: "Who has the most Super Bowl wins as a QB?", solutions: ["Tom Brady"] },
    { text: "Name a team with the top 3 most Super Bowl appearances.", solutions: ["New England Patriots", "Dallas Cowboys", "Pittsburgh Steelers"] },
    { text: "Who ran the fastest 40-yard dash at the NFL Combine?", solutions: ["John Ross"] },
    { text: "Name one of the top 3 players with the most career sacks.", solutions: ["Bruce Smith", "Reggie White", "DeMarcus Ware"] },
    { text: "Which team has the most playoff wins since 2000?", solutions: ["New England Patriots"] },
    { text: "Who was the NFL MVP in 2023?", solutions: ["Patrick Mahomes"] }, // Assuming trend
    { text: "Name a QB with a 5,000-yard passing season.", solutions: ["Peyton Manning", "Tom Brady", "Drew Brees"] },
    { text: "Which team won back-to-back Super Bowls in the 2000s?", solutions: ["New England Patriots"] },
    { text: "Who has the most receiving yards in a single season?", solutions: ["Calvin Johnson"] },
    { text: "Name a player who won both NFL MVP and Super Bowl MVP in the same year.", solutions: ["Patrick Mahomes", "Tom Brady"] },
    { text: "Name one of the top 3 teams with the most primetime wins since 2010.", solutions: ["New England Patriots", "Seattle Seahawks", "Green Bay Packers"] },
    { text: "Who has the most interceptions returned for touchdowns?", solutions: ["Rod Woodson"] },
    { text: "Name a team that played in a Super Bowl in the 2020s.", solutions: ["Kansas City Chiefs", "San Francisco 49ers", "Philadelphia Eagles"] },
    { text: "Who has the most career passing yards?", solutions: ["Tom Brady"] },
    { text: "Name a player with a 300+ yard rushing game.", solutions: ["Adrian Peterson", "Jamal Lewis", "Walter Payton"] },
    { text: "Which team has never been to a Super Bowl?", solutions: ["Cleveland Browns"] },
    { text: "Name one of the top 5 players with the most career tackles.", solutions: ["Ray Lewis", "Junior Seau", "London Fletcher", "Zach Thomas", "Patrick Willis"] },
    { text: "Who won Super Bowls with two different teams as a QB?", solutions: ["Tom Brady"] },
    { text: "Name a team with the top 3 most Hall of Famers.", solutions: ["Chicago Bears", "Green Bay Packers", "New York Giants"] },
    { text: "Who has the most punt return touchdowns?", solutions: ["Devin Hester"] },
    { text: "Name one of the top 5 QBs with the most career touchdown passes.", solutions: ["Tom Brady", "Peyton Manning", "Brett Favre", "Drew Brees", "Dan Marino"] },
    { text: "Name an RB who won the NFL MVP award.", solutions: ["Adrian Peterson", "LaDainian Tomlinson"] },
    { text: "Which team has the most Monday Night Football wins?", solutions: ["San Francisco 49ers"] },
    { text: "Name a QB with the top 3 most passing touchdowns in 2022.", solutions: ["Patrick Mahomes", "Joe Burrow", "Josh Allen"] },
    { text: "Which team won the Super Bowl in 2020?", solutions: ["Kansas City Chiefs"] },
    { text: "Who has the most career receiving touchdowns?", solutions: ["Jerry Rice"] },
    { text: "Name one of the top 3 players with the most Pro Bowl selections.", solutions: ["Tony Gonzalez", "Peyton Manning", "Bruce Matthews"] },
    { text: "Which team has the longest winning streak in NFL history?", solutions: ["New England Patriots"] },
    { text: "Who was the first overall pick in the 2023 NFL Draft?", solutions: ["Bryce Young"] },
    { text: "Name a QB with the top 3 most comeback wins.", solutions: ["Tom Brady", "Peyton Manning", "John Elway"] },
    { text: "Name a team with the top 5 most division titles.", solutions: ["Dallas Cowboys", "Green Bay Packers", "Pittsburgh Steelers", "New England Patriots", "San Francisco 49ers"] },
    { text: "Who has the most career field goals?", solutions: ["Adam Vinatieri"] },
    { text: "Name a Defensive Player of the Year from the 2020s.", solutions: ["Nick Bosa", "T.J. Watt"] },
    { text: "Which team has the most road playoff wins?", solutions: ["New England Patriots"] },
    { text: "Name one of the top 3 players with the most career rushing touchdowns.", solutions: ["Emmitt Smith", "LaDainian Tomlinson", "Walter Payton"] },
    { text: "Name a QB with the top 3 most passing yards in a playoff game.", solutions: ["Tom Brady", "Joe Flacco", "Eli Manning"] },
    { text: "Which team has the most Super Bowl losses?", solutions: ["Denver Broncos"] },
    { text: "Who has the most career punt return yards?", solutions: ["Brian Mitchell"] },
    { text: "Name a player with the top 3 most consecutive games with a touchdown.", solutions: ["Jerry Rice", "Terrell Owens", "Randy Moss"] },
    { text: "Which team won the Super Bowl in 2019?", solutions: ["New England Patriots"] },
    { text: "Name one of the top 3 players with the most career interception return yards.", solutions: ["Rod Woodson", "Deion Sanders", "Aqib Talib"] },
    { text: "Who has the highest single-season passer rating?", solutions: ["Aaron Rodgers"] },
    { text: "Name a team with the top 3 most AFC Championship wins.", solutions: ["New England Patriots", "Pittsburgh Steelers", "Denver Broncos"] },
    { text: "Who has the most career kickoff return touchdowns?", solutions: ["Josh Cribbs"] },
    { text: "Name an Offensive Rookie of the Year from the 2020s.", solutions: ["Justin Jefferson", "Ja’Marr Chase"] },
    { text: "Which team has the most consecutive playoff appearances?", solutions: ["New England Patriots"] },
    { text: "Name one of the top 3 QBs with the most career passing attempts.", solutions: ["Brett Favre", "Tom Brady", "Peyton Manning"] },
    { text: "Name a QB with the top 3 most fourth-quarter comebacks.", solutions: ["Tom Brady", "Peyton Manning", "John Elway"] },
    { text: "Which team has the most overtime wins?", solutions: ["Denver Broncos"] }
  ],
  "Golf": [
    { text: "Name one of the top 3 golfers with the most Masters Tournament wins.", solutions: ["Jack Nicklaus", "Tiger Woods", "Arnold Palmer"] },
    { text: "What is the maximum number of clubs allowed in a golf bag?", solutions: ["14"] },
    { text: "Who has the most career PGA Tour wins?", solutions: ["Sam Snead"] },
    { text: "Name a golfer who has won the Career Grand Slam.", solutions: ["Jack Nicklaus", "Tiger Woods", "Gary Player"] },
    { text: "Who won the 2023 Masters Tournament?", solutions: ["Jon Rahm"] },
    { text: "What is the standard par for a golf course?", solutions: ["72"] },
    { text: "Name one of the top 3 lowest single-round scores in a major.", solutions: ["Brandt Snedeker", "Xander Schauffele", "Rory McIlroy"] },
    { text: "Who has the most major championships?", solutions: ["Jack Nicklaus"] },
    { text: "What is the typical distance range of a par-4 golf hole?", solutions: ["400-500 yards"] },
    { text: "Who won the 2022 PGA Championship?", solutions: ["Justin Thomas"] },
    { text: "Name a golfer with the top 3 most Ryder Cup points.", solutions: ["Nick Faldo", "Sergio Garcia", "Colin Montgomerie"] },
    { text: "What is the first golf major of the year called?", solutions: ["Masters"] },
    { text: "Name one of the top 3 golfers with the most U.S. Open wins.", solutions: ["Willie Anderson", "Bobby Jones", "Ben Hogan"] },
    { text: "Who has the longest recorded drive in professional golf?", solutions: ["Mike Austin"] },
    { text: "Who won the 2023 Open Championship?", solutions: ["Brian Harman"] },
    { text: "What is the standard diameter of a golf ball?", solutions: ["1.68 inches"] },
    { text: "Name a golfer with the top 3 most consecutive cuts made.", solutions: ["Tiger Woods", "Jack Nicklaus", "Gary Player"] },
    { text: "Who was a key designer of the Augusta National Golf Club?", solutions: ["Bobby Jones"] },
    { text: "What is the highest score typically recorded on a single hole?", solutions: ["20"] },
    { text: "Name a golfer with the top 3 most Presidents Cup wins.", solutions: ["Tiger Woods", "Phil Mickelson", "Steve Stricker"] },
    { text: "Who won the 2022 U.S. Open?", solutions: ["Matt Fitzpatrick"] },
    { text: "What is the name of the famous 12th hole at Augusta?", solutions: ["Golden Bell"] },
    { text: "Name one of the top 3 golfers with the most top-10 finishes in majors.", solutions: ["Jack Nicklaus", "Tiger Woods", "Phil Mickelson"] },
    { text: "What is the maximum score per hole in match play?", solutions: ["No limit"] },
    { text: "Who has the most PGA Player of the Year awards?", solutions: ["Tiger Woods"] },
    { text: "Which course has hosted the PGA Championship multiple times?", solutions: ["Oak Hill"] },
    { text: "Who won the 2021 Masters Tournament?", solutions: ["Hideki Matsuyama"] },
    { text: "What is the standard length of a golf tee?", solutions: ["2.75 inches"] },
    { text: "Name a golfer with the top 3 most holes-in-one.", solutions: ["Robert Allenby", "Hal Sutton", "Gary Player"] },
    { text: "Who designed the Pebble Beach Golf Links?", solutions: ["Jack Neville"] },
    { text: "What is the score for a hole-in-one?", solutions: ["1"] },
    { text: "Name a golfer with the top 3 most European Tour wins.", solutions: ["Seve Ballesteros", "Bernhard Langer", "Colin Montgomerie"] },
    { text: "Who won the 2020 PGA Championship?", solutions: ["Collin Morikawa"] },
    { text: "What is the name of the 18th hole at St. Andrews?", solutions: ["Tom Morris"] },
    { text: "Name a golfer with the top 3 most senior major wins.", solutions: ["Gary Player", "Bernhard Langer", "Hale Irwin"] },
    { text: "What is the weight of a golf ball?", solutions: ["1.62 ounces"] },
    { text: "Name one of the top 3 golfers with the most consecutive major appearances.", solutions: ["Jack Nicklaus", "Tiger Woods", "Arnold Palmer"] },
    { text: "Which course has hosted the U.S. Open multiple times?", solutions: ["Pebble Beach"] },
    { text: "Who won the 2019 Open Championship?", solutions: ["Shane Lowry"] },
    { text: "What is the diameter of a golf hole?", solutions: ["4.25 inches"] },
    { text: "Name a golfer with the top 3 most international wins.", solutions: ["Gary Player", "Seve Ballesteros", "Greg Norman"] },
    { text: "Who designed the Pinehurst No. 2 course?", solutions: ["Donald Ross"] },
    { text: "What is the score for an albatross?", solutions: ["-3"] },
    { text: "Name a golfer who has won PGA Tour Rookie of the Year.", solutions: ["Tiger Woods", "Jordan Spieth"] },
    { text: "Who won the 2022 Masters Tournament?", solutions: ["Scottie Scheffler"] },
    { text: "What is the typical length range of a standard putter?", solutions: ["34-35 inches"] },
    { text: "Who has the most career earnings on the PGA Tour?", solutions: ["Tiger Woods"] },
    { text: "Who designed the TPC Sawgrass?", solutions: ["Pete Dye"] },
    { text: "What is the score for a condor?", solutions: ["-4"] },
    { text: "Name a golfer with the top 3 most amateur wins.", solutions: ["Bobby Jones", "Tiger Woods", "Phil Mickelson"] }
  ],
  "Soccer": [
    { text: "Name one of the top 3 players with the most Ballon d'Or awards.", solutions: ["Lionel Messi", "Cristiano Ronaldo", "Johan Cruyff"] },
    { text: "Which country has the most FIFA World Cup titles?", solutions: ["Brazil"] },
    { text: "Who is the all-time leading goalscorer for the English Premier League?", solutions: ["Alan Shearer"] },
    { text: "Name a club with the top 3 most UEFA Champions League titles.", solutions: ["Real Madrid", "AC Milan", "Liverpool"] },
    { text: "Who won the 2022 FIFA World Cup Golden Boot?", solutions: ["Kylian Mbappé"] },
    { text: "Name one of the top 3 players with the most international goals.", solutions: ["Cristiano Ronaldo", "Lionel Messi", "Ali Daei"] },
    { text: "What is the duration of a standard soccer match?", solutions: ["90 minutes"] },
    { text: "Which country hosted the 2022 FIFA World Cup?", solutions: ["Qatar"] },
    { text: "Who is the current captain of the Brazil national team?", solutions: ["Casemiro"] }, // Assuming 2025
    { text: "Name a club with the top 5 most English Premier League titles.", solutions: ["Manchester United", "Liverpool", "Arsenal", "Chelsea", "Manchester City"] },
    { text: "Who won the 2023 Ballon d'Or?", solutions: ["Lionel Messi"] }, // Assuming trend
    { text: "Name one of the top 3 players with the most assists in La Liga history.", solutions: ["Lionel Messi", "Xavi Hernández", "Ángel Di María"] },
    { text: "What does the offside rule in soccer prevent?", solutions: ["Unfair advantage"] },
    { text: "Which country won the UEFA Euro 2020?", solutions: ["Italy"] },
    { text: "Who is the all-time leading goalscorer for Real Madrid?", solutions: ["Cristiano Ronaldo"] },
    { text: "Name a club with the top 3 most Copa Libertadores titles.", solutions: ["Independiente", "Boca Juniors", "Peñarol"] },
    { text: "Who won the 2022 FIFA World Cup Golden Glove?", solutions: ["Emiliano Martínez"] },
    { text: "Name one of the top 3 players with the most red cards in their career.", solutions: ["Gerardo Bedoya", "Sergio Ramos", "Pepe"] },
    { text: "What is the size of a standard soccer goal?", solutions: ["8x24 feet"] },
    { text: "Which country hosted the 2018 FIFA World Cup?", solutions: ["Russia"] },
    { text: "Who is the current manager of Manchester City?", solutions: ["Pep Guardiola"] }, // Assuming 2025
    { text: "Name a club with the top 3 most FA Cup titles.", solutions: ["Arsenal", "Manchester United", "Chelsea"] },
    { text: "Who won the 2021 Ballon d'Or?", solutions: ["Lionel Messi"] },
    { text: "Name one of the top 3 players with the most hat-tricks in the Premier League.", solutions: ["Alan Shearer", "Harry Kane", "Sergio Agüero"] },
    { text: "What is the maximum number of substitutes in a soccer match?", solutions: ["5"] },
    { text: "Which country won the 2014 FIFA World Cup?", solutions: ["Germany"] },
    { text: "Who is the all-time leading goalscorer for Barcelona?", solutions: ["Lionel Messi"] },
    { text: "Name a club with the top 3 most La Liga titles.", solutions: ["Real Madrid", "Barcelona", "Atlético Madrid"] },
    { text: "Who won the 2022 UEFA Champions League?", solutions: ["Real Madrid"] },
    { text: "Name one of the top 3 players with the most international assists.", solutions: ["Lionel Messi", "Kevin De Bruyne", "Neymar"] },
    { text: "What is the diameter of a soccer ball?", solutions: ["8.6-9 inches"] },
    { text: "Which country hosted the 2010 FIFA World Cup?", solutions: ["South Africa"] },
    { text: "Who is the current captain of the Argentina national team?", solutions: ["Lionel Messi"] },
    { text: "Name a club with the top 3 most Coppa Italia titles.", solutions: ["Juventus", "AS Roma", "Inter Milan"] },
    { text: "Who won the 2023 FIFA The Best Men's Player award?", solutions: ["Lionel Messi"] }, // Assuming trend
    { text: "Name one of the top 3 players with the most goals in a single Premier League season.", solutions: ["Erling Haaland", "Mohamed Salah", "Harry Kane"] },
    { text: "What is the length of a soccer field?", solutions: ["100-110 meters"] },
    { text: "Which country won the 2006 FIFA World Cup?", solutions: ["Italy"] },
    { text: "Who is the all-time leading goalscorer for Manchester United?", solutions: ["Wayne Rooney"] },
    { text: "Name a club with the top 3 most Bundesliga titles.", solutions: ["Bayern Munich", "Borussia Dortmund", "Hamburger SV"] },
    { text: "Who won the 2022 Ballon d'Or?", solutions: ["Karim Benzema"] },
    { text: "Name one of the top 3 goalkeepers with the most clean sheets in Premier League history.", solutions: ["Petr Čech", "David James", "Mark Schwarzer"] },
    { text: "What is the weight of a soccer ball?", solutions: ["14-16 ounces"] },
    { text: "Which countries co-hosted the 2002 FIFA World Cup?", solutions: ["South Korea/Japan"] },
    { text: "Who is the current manager of Liverpool?", solutions: ["Jürgen Klopp"] }, // Assuming 2025
    { text: "Name a club with the top 3 most Ligue 1 titles.", solutions: ["Paris Saint-Germain", "Saint-Étienne", "Marseille"] },
    { text: "Who won the 2021 UEFA Euro Golden Boot?", solutions: ["Cristiano Ronaldo"] },
    { text: "Name one of the top 3 players with the most appearances in the Premier League.", solutions: ["James Milner", "Gareth Barry", "Ryan Giggs"] },
    { text: "What is the number of players on a soccer field per team?", solutions: ["11"] },
    { text: "Which country won the 1998 FIFA World Cup?", solutions: ["France"] }
  ],
  "Basketball": [
    { text: "Name one of the top 3 players with the most career points in the NBA.", solutions: ["LeBron James", "Kareem Abdul-Jabbar", "Karl Malone"] },
    { text: "Which team has the most NBA Championships?", solutions: ["Boston Celtics"] },
    { text: "Who is the all-time leading rebounder in the NBA?", solutions: ["Wilt Chamberlain"] },
    { text: "Name a player with the top 3 most MVP awards.", solutions: ["Kareem Abdul-Jabbar", "Bill Russell", "Michael Jordan"] },
    { text: "Who won the 2023 NBA Finals MVP?", solutions: ["Nikola Jokić"] }, // Based on 2023
    { text: "What is the duration of an NBA quarter?", solutions: ["12 minutes"] },
    { text: "Name one of the top 3 players with the most career assists.", solutions: ["John Stockton", "Chris Paul", "LeBron James"] },
    { text: "Which team has the most consecutive NBA titles?", solutions: ["Boston Celtics"] },
    { text: "Who has the highest single-game scoring record?", solutions: ["Wilt Chamberlain"] },
    { text: "Who won the 2022 NBA Rookie of the Year?", solutions: ["Scottie Barnes"] },
    { text: "What is the height of an NBA hoop?", solutions: ["10 feet"] },
    { text: "Which team won the NBA Championship in 2022?", solutions: ["Golden State Warriors"] },
    { text: "Name one of the top 3 players with the most three-pointers made in a season.", solutions: ["Stephen Curry", "James Harden", "Damian Lillard"] },
    { text: "Name a player with the top 3 most All-Star selections.", solutions: ["Kareem Abdul-Jabbar", "LeBron James", "Kobe Bryant"] },
    { text: "What is the diameter of an NBA basketball?", solutions: ["9.4 inches"] },
    { text: "Name a team with the top 3 most Western Conference titles.", solutions: ["Los Angeles Lakers", "Golden State Warriors", "San Antonio Spurs"] },
    { text: "Who won the 2023 NBA Sixth Man of the Year?", solutions: ["Malik Monk"] }, // Assuming trend
    { text: "Name one of the top 3 players with the most career steals.", solutions: ["John Stockton", "Jason Kidd", "Chris Paul"] },
    { text: "What is the maximum number of fouls before fouling out?", solutions: ["6"] },
    { text: "Which team won the NBA Championship in 2020?", solutions: ["Los Angeles Lakers"] },
    { text: "Who has the most career blocks?", solutions: ["Hakeem Olajuwon"] },
    { text: "Who won the 2022 NBA Defensive Player of the Year?", solutions: ["Marcus Smart"] },
    { text: "What is the length of an NBA court?", solutions: ["94 feet"] },
    { text: "Name a team with the top 3 most playoff appearances.", solutions: ["Los Angeles Lakers", "Boston Celtics", "Philadelphia 76ers"] },
    { text: "Who won the 2021 NBA Finals MVP?", solutions: ["Giannis Antetokounmpo"] },
    { text: "Name one of the top 3 players with the most career double-doubles.", solutions: ["Wilt Chamberlain", "Bill Russell", "Tim Duncan"] },
    { text: "What is the weight of an NBA basketball?", solutions: ["22 ounces"] },
    { text: "Which team won the NBA Championship in 2019?", solutions: ["Toronto Raptors"] },
    { text: "Name one of the top 3 players with the most career triple-doubles.", solutions: ["Russell Westbrook", "LeBron James", "Nikola Jokić"] },
    { text: "Who won the 2023 NBA Most Improved Player?", solutions: ["Lauri Markkanen"] }, // Assuming trend
    { text: "What is the three-point line distance in the NBA?", solutions: ["23.75 feet"] },
    { text: "Name a team with the top 3 most Eastern Conference titles.", solutions: ["Boston Celtics", "Miami Heat", "Cleveland Cavaliers"] },
    { text: "Who won the 2022 NBA Clutch Player of the Year?", solutions: ["DeMar DeRozan"] },
    { text: "Name one of the top 3 players with the most career free throws made.", solutions: ["Kareem Abdul-Jabbar", "Karl Malone", "Kobe Bryant"] },
    { text: "What is the number of players on an NBA team on the court?", solutions: ["5"] },
    { text: "Which team won the NBA Championship in 2018?", solutions: ["Golden State Warriors"] },
    { text: "Who has the most career minutes played?", solutions: ["Kareem Abdul-Jabbar"] },
    { text: "Who won the 2021 NBA Rookie of the Year?", solutions: ["LaMelo Ball"] },
    { text: "What is the width of an NBA court?", solutions: ["50 feet"] },
    { text: "Name a team with the top 3 most All-Star game appearances.", solutions: ["Los Angeles Lakers", "Boston Celtics", "Chicago Bulls"] },
    { text: "Who won the 2023 NBA Coach of the Year?", solutions: ["Mike Brown"] }, // Assuming trend
    { text: "Name one of the top 3 players with the most career field goals made.", solutions: ["Kareem Abdul-Jabbar", "Karl Malone", "LeBron James"] },
    { text: "What is the shot clock duration in the NBA?", solutions: ["24 seconds"] },
    { text: "Which team won the NBA Championship in 2017?", solutions: ["Golden State Warriors"] },
    { text: "Name one of the top 3 players with the most career turnovers.", solutions: ["LeBron James", "Karl Malone", "John Stockton"] },
    { text: "Who won the 2022 NBA Sixth Man of the Year?", solutions: ["Tyler Herro"] },
    { text: "What is the distance of the NBA free-throw line from the hoop?", solutions: ["15 feet"] },
    { text: "Name a team with the top 3 most NBA Finals appearances.", solutions: ["Los Angeles Lakers", "Boston Celtics", "Golden State Warriors"] },
    { text: "Who won the 2021 NBA Defensive Player of the Year?", solutions: ["Rudy Gobert"] },
    { text: "Name one of the top 3 players with the most career personal fouls.", solutions: ["Kareem Abdul-Jabbar", "Karl Malone", "Robert Parish"] }
  ],
  "CollegeFootball": [
    { text: "Name one of the top 5 college football programs with the most national championships.", solutions: ["Alabama", "Notre Dame", "USC", "Ohio State", "Oklahoma"] },
    { text: "Who has the most career passing yards in college football history?", solutions: ["Case Keenum"] },
    { text: "Name a player with the top 3 most Heisman Trophy wins.", solutions: ["Archie Griffin"] },
    { text: "Which team won the 2022 College Football Playoff National Championship?", solutions: ["Georgia"] },
    { text: "Name one of the top 3 coaches with the most wins in college football history.", solutions: ["Joe Paterno", "Bobby Bowden", "Nick Saban"] },
    { text: "What is the duration of a college football quarter?", solutions: ["15 minutes"] },
    { text: "Name a player with the top 3 most career rushing yards in college football.", solutions: ["Ron Dayne", "Ricky Williams", "Tony Dorsett"] },
    { text: "Which team has the most consecutive national championships?", solutions: ["Yale"] },
    { text: "Who has the most single-game passing yards in college football?", solutions: ["Connor Halliday"] },
    { text: "Who won the 2022 Heisman Trophy?", solutions: ["Caleb Williams"] },
    { text: "What is the length of a college football field (excluding end zones)?", solutions: ["100 yards"] },
    { text: "Which team won the 2021 College Football Playoff National Championship?", solutions: ["Alabama"] },
    { text: "Name one of the top 3 players with the most career receiving yards in college football.", solutions: ["Corey Davis", "Zay Flowers", "Ryan Broyles"] },
    { text: "Name a player with the top 3 most All-American selections.", solutions: ["Herschel Walker", "Orlando Pace", "Reggie Bush"] },
    { text: "What is the width of a college football field?", solutions: ["53.3 yards"] },
    { text: "Name a team with the top 3 most SEC titles.", solutions: ["Alabama", "Georgia", "Tennessee"] },
    { text: "Who won the 2023 Maxwell Award?", solutions: ["Caleb Williams"] }, // Assuming trend
    { text: "Name one of the top 3 players with the most career interceptions in college football.", solutions: ["Al Brosky", "Martin Bayless", "Terrell Buckley"] },
    { text: "What is the maximum number of timeouts per half in college football?", solutions: ["3"] },
    { text: "Which team won the 2020 College Football Playoff National Championship?", solutions: ["LSU"] },
    { text: "Who has the most career sacks in college football?", solutions: ["Terrell Suggs"] },
    { text: "Who won the 2022 Bednarik Award?", solutions: ["Will Anderson Jr."] },
    { text: "What is the distance of a college football extra point attempt?", solutions: ["20 yards"] },
    { text: "Name a team with the top 3 most bowl game appearances.", solutions: ["Alabama", "Texas", "Georgia"] },
    { text: "Who won the 2021 Heisman Trophy?", solutions: ["Bryce Young"] },
    { text: "Name one of the top 3 players with the most career total touchdowns.", solutions: ["Case Keenum", "Timmy Chang", "Colt Brennan"] },
    { text: "What is the weight of a college football?", solutions: ["14-15 ounces"] },
    { text: "Which team won the 2019 College Football Playoff National Championship?", solutions: ["Clemson"] },
    { text: "Name one of the top 3 players with the most career tackles in college football.", solutions: ["Luke Kuechly", "Derrick Thomas", "Aaron Taylor"] },
    { text: "Who won the 2023 Outland Trophy?", solutions: ["Olumuyiwa Fashanu"] }, // Assuming trend
    { text: "What is the overtime format in college football?", solutions: ["Alternating possessions"] },
    { text: "Name a team with the top 3 most Big Ten titles.", solutions: ["Michigan", "Ohio State", "Penn State"] },
    { text: "Who won the 2022 Biletnikoff Award?", solutions: ["Jalin Hyatt"] },
    { text: "Name one of the top 3 players with the most career passing touchdowns.", solutions: ["Case Keenum", "Kellen Moore", "Colt Brennan"] },
    { text: "What is the number of players on a college football team on the field?", solutions: ["11"] },
    { text: "Which team won the 2018 College Football Playoff National Championship?", solutions: ["Alabama"] },
    { text: "Who has the most career punt return yards in college football?", solutions: ["Wes Welker"] },
    { text: "Who won the 2021 Bednarik Award?", solutions: ["Jordan Davis"] },
    { text: "What is the height of the goalposts in college football?", solutions: ["30 feet"] },
    { text: "Name a team with the top 3 most ACC titles.", solutions: ["Clemson", "Florida State", "Miami"] },
    { text: "Who won the 2023 Jim Thorpe Award?", solutions: ["Cooper DeJean"] }, // Assuming trend
    { text: "Name one of the top 3 players with the most career rushing touchdowns.", solutions: ["Montee Ball", "Travis Prentice", "Ricky Williams"] },
    { text: "What is the shot clock equivalent in college football?", solutions: ["Play clock: 40 seconds"] },
    { text: "Which team won the 2017 College Football Playoff National Championship?", solutions: ["Clemson"] },
    { text: "Name one of the top 3 players with the most career interceptions returned for touchdowns.", solutions: ["Terrell Buckley", "Derrick Thomas", "Charles Woodson"] },
    { text: "Who won the 2022 Doak Walker Award?", solutions: ["Bijan Robinson"] },
    { text: "What is the distance of a college football field goal attempt from the 50-yard line?", solutions: ["Varies"] },
    { text: "Name a team with the top 3 most Pac-12 titles.", solutions: ["USC", "Stanford", "Washington"] },
    { text: "Who won the 2021 Outland Trophy?", solutions: ["Jordan Davis"] },
    { text: "Name one of the top 3 players with the most career receiving touchdowns.", solutions: ["Jarett Dillard", "Corey Davis", "Troy Edwards"] }
  ],
  "CollegeBasketball": [
    { text: "Name one of the top 5 college basketball programs with the most NCAA championships.", solutions: ["UCLA", "Kentucky", "North Carolina", "Duke", "Kansas"] },
    { text: "Who has the most career points in NCAA men's basketball history?", solutions: ["Pete Maravich"] },
    { text: "Name a player with the top 3 most Wooden Awards.", solutions: ["Ralph Sampson", "Kevin Durant"] },
    { text: "Which team won the 2023 NCAA Men's Basketball Championship?", solutions: ["UConn"] },
    { text: "Name one of the top 3 coaches with the most wins in NCAA men's basketball history.", solutions: ["Mike Krzyzewski", "Jim Boeheim", "Roy Williams"] },
    { text: "What is the duration of a college basketball half?", solutions: ["20 minutes"] },
    { text: "Name a player with the top 3 most career rebounds in NCAA men's basketball.", solutions: ["Bill Russell", "Elvin Hayes", "Tim Duncan"] },
    { text: "Which team has the most consecutive NCAA championships?", solutions: ["UCLA"] },
    { text: "Who has the most single-game points in NCAA men's basketball?", solutions: ["Frank Selvy"] },
    { text: "Who won the 2022 Naismith College Player of the Year?", solutions: ["Oscar Tshiebwe"] },
    { text: "What is the height of a college basketball hoop?", solutions: ["10 feet"] },
    { text: "Which team won the 2021 NCAA Men's Basketball Championship?", solutions: ["Baylor"] },
    { text: "Name one of the top 3 players with the most career assists in NCAA men's basketball.", solutions: ["Bobby Hurley", "Chris Paul", "Jason Kidd"] },
    { text: "Name a player with the top 3 most All-American selections.", solutions: ["Tyler Hansbrough", "J.J. Redick", "Christian Laettner"] },
    { text: "What is the diameter of a college basketball?", solutions: ["9.4 inches"] },
    { text: "Name a team with the top 3 most ACC titles.", solutions: ["Duke", "North Carolina", "Virginia"] },
    { text: "Who won the 2023 Naismith College Coach of the Year?", solutions: ["Jerome Tang"] }, // Assuming trend
    { text: "Name one of the top 3 players with the most career steals in NCAA men's basketball.", solutions: ["John Linehan", "Eric Murdock", "Mookie Blaylock"] },
    { text: "What is the maximum number of fouls before fouling out in college basketball?", solutions: ["5"] },
    { text: "Which team won the 2020 NCAA Men's Basketball Championship?", solutions: ["Canceled"] }, // Due to COVID-19
    { text: "Who has the most career blocks in NCAA men's basketball?", solutions: ["David Robinson"] },
    { text: "Who won the 2022 Wooden Award?", solutions: ["Oscar Tshiebwe"] },
    { text: "What is the length of a college basketball court?", solutions: ["94 feet"] },
    { text: "Name a team with the top 3 most NCAA Tournament appearances.", solutions: ["Kentucky", "North Carolina", "UCLA"] },
    { text: "Who won the 2021 Naismith College Player of the Year?", solutions: ["Luka Garza"] },
    { text: "Name one of the top 3 players with the most career double-doubles in NCAA men's basketball.", solutions: ["Tim Duncan", "David Robinson", "Bill Walton"] },
    { text: "What is the weight of a college basketball?", solutions: ["22 ounces"] },
    { text: "Which team won the 2019 NCAA Men's Basketball Championship?", solutions: ["Virginia"] },
    { text: "Name one of the top 3 players with the most career triple-doubles in NCAA men's basketball.", solutions: ["Kyle Collinsworth", "Shaquille O'Neal", "Dwayne Davis"] },
    { text: "Who won the 2023 NABC Defensive Player of the Year?", solutions: ["Jaylen Clark"] }, // Assuming trend
    { text: "What is the three-point line distance in college basketball?", solutions: ["22.15 feet"] },
    { text: "Name a team with the top 3 most Big Ten titles.", solutions: ["Purdue", "Indiana", "Michigan State"] },
    { text: "Who won the 2022 NABC Player of the Year?", solutions: ["Oscar Tshiebwe"] },
    { text: "Name one of the top 3 players with the most career free throws made in NCAA men's basketball.", solutions: ["Pete Maravich", "Tyler Hansbrough", "Chris Mullin"] },
    { text: "What is the number of players on a college basketball team on the court?", solutions: ["5"] },
    { text: "Which team won the 2018 NCAA Men's Basketball Championship?", solutions: ["Villanova"] },
    { text: "Who has the most career minutes played in NCAA men's basketball?", solutions: ["Tyler Hansbrough"] },
    { text: "Who won the 2021 Wooden Award?", solutions: ["Luka Garza"] },
    { text: "What is the width of a college basketball court?", solutions: ["50 feet"] },
    { text: "Name a team with the top 3 most Final Four appearances.", solutions: ["North Carolina", "UCLA", "Kentucky"] },
    { text: "Who won the 2023 Naismith College Coach of the Year?", solutions: ["Jerome Tang"] }, // Assuming trend
    { text: "Name one of the top 3 players with the most career field goals made in NCAA men's basketball.", solutions: ["Pete Maravich", "Freeman Williams", "Lionel Simmons"] },
    { text: "What is the shot clock duration in college basketball?", solutions: ["30 seconds"] },
    { text: "Which team won the 2017 NCAA Men's Basketball Championship?", solutions: ["North Carolina"] },
    { text: "Name one of the top 3 players with the most career turnovers in NCAA men's basketball.", solutions: ["Bobby Hurley", "Sherman Douglas", "Gary Payton"] },
    { text: "Who won the 2022 NABC Defensive Player of the Year?", solutions: ["Walker Kessler"] },
    { text: "What is the distance of the college basketball free-throw line from the hoop?", solutions: ["15 feet"] },
    { text: "Name a team with the top 3 most SEC titles.", solutions: ["Kentucky", "Florida", "Arkansas"] },
    { text: "Who won the 2021 NABC Player of the Year?", solutions: ["Luka Garza"] },
    { text: "Name one of the top 3 players with the most career personal fouls in NCAA men's basketball.", solutions: ["David Robinson", "Tim Duncan", "Shaquille O'Neal"] }
  ]
};
